--CREATE A STUDENTS TABLE
CREATE TABLE STUDENTS
(
ID INT PRIMARY KEY,
STUD_NAME VARCHAR(10) NOT NULL UNIQUE,
GENDER CHAR(1) NOT NULL,
AGE INT NOT NULL,
CLASS VARCHAR(10) NOT NULL,
CONSTRAINT CHECK_GENDER CHECK(GENDER IN ('M','F'))
)

--INSERT SOME SAMPLE RECORDS
INSERT INTO STUDENTS (ID,STUD_NAME,GENDER,AGE,CLASS) 
VALUES (1, 'NAME_ONE','M',24,'10TH'), (2, 'NAME_TWO','F',24,'10TH'),(3, 'NAME_THREE','M',25,'11TH'),
(4, 'NAME_FOUR','F',24,'12TH'),(5, 'NAME_FIVE','F',24,'9TH');

WITH FIRST_CTE 
AS
(
SELECT * FROM STUDENTS WHERE CLASS LIKE '10%'
)
SELECT * FROM FIRST_CTE

WITH FIRST_CTE 
AS
(
SELECT * FROM STUDENTS WHERE GENDER = 'F'
)
SELECT * FROM FIRST_CTE


WITH FIRST_CTE (STUDENT_ID, STUDENT_NAME, STUDENT_CLASS)
AS
(
SELECT ID, STUD_NAME, CLASS FROM STUDENTS WHERE GENDER = 'F'
)
SELECT * FROM FIRST_CTE

--INSERT, UPDATE AND DELETE USING CTE

WITH FIRST_CTE
AS
(
SELECT * FROM STUDENTS
)
INSERT FIRST_CTE VALUES (6,'ABHISHEK','M',24,'12TH')
UPDATE FIRST_CTE SET STUD_NAME = 'ABHI R M' WHERE ID = 6
DELETE FIRST_CTE WHERE ID = 5

--CREATING VIEW FOR CTE

CREATE VIEW CTE_VIEW 
AS
WITH FIRST_CTE
AS
(
SELECT * FROM STUDENTS WHERE GENDER='M'
)
SELECT * FROM FIRST_CTE
SELECT * FROM CTE_VIEW

--CREATING MULTIPLE CTE'S

WITH FIRST_CTE
AS
(
SELECT * FROM STUDENTS WHERE GENDER='M'
),
SECOND_CTE 
AS
(
SELECT * FROM STUDENTS WHERE GENDER='M' AND CLASS = '12TH'
)
SELECT * FROM FIRST_CTE UNION ALL SELECT * FROM SECOND_CTE


